2023-10-18 15:06:40,822 INFO    MainThread:280016 [wandb_setup.py:_flush():76] Current SDK version is 0.15.10
2023-10-18 15:06:40,822 INFO    MainThread:280016 [wandb_setup.py:_flush():76] Configure stats pid to 280016
2023-10-18 15:06:40,822 INFO    MainThread:280016 [wandb_setup.py:_flush():76] Loading settings from C:\Users\sari\.config\wandb\settings
2023-10-18 15:06:40,823 INFO    MainThread:280016 [wandb_setup.py:_flush():76] Loading settings from C:\Users\sari\Desktop\DeepCover\wandb\settings
2023-10-18 15:06:40,823 INFO    MainThread:280016 [wandb_setup.py:_flush():76] Loading settings from environment variables: {}
2023-10-18 15:06:40,823 INFO    MainThread:280016 [wandb_setup.py:_flush():76] Applying setup settings: {'_disable_service': False}
2023-10-18 15:06:40,823 INFO    MainThread:280016 [wandb_setup.py:_flush():76] Inferring run settings from compute environment: {'program_relpath': 'main.py', 'program': 'C:\\Users\\sari\\Desktop\\DeepCover\\main.py'}
2023-10-18 15:06:40,823 INFO    MainThread:280016 [wandb_init.py:_log_setup():524] Logging user logs to C:\Users\sari\Desktop\DeepCover\wandb\run-20231018_150640-tje2dr2l\logs\debug.log
2023-10-18 15:06:40,824 INFO    MainThread:280016 [wandb_init.py:_log_setup():525] Logging internal logs to C:\Users\sari\Desktop\DeepCover\wandb\run-20231018_150640-tje2dr2l\logs\debug-internal.log
2023-10-18 15:06:40,824 INFO    MainThread:280016 [wandb_init.py:init():564] calling init triggers
2023-10-18 15:06:40,824 INFO    MainThread:280016 [wandb_init.py:init():571] wandb.init called with sweep_config: {}
config: {}
2023-10-18 15:06:40,824 INFO    MainThread:280016 [wandb_init.py:init():614] starting backend
2023-10-18 15:06:40,824 INFO    MainThread:280016 [wandb_init.py:init():618] setting up manager
2023-10-18 15:06:40,826 INFO    MainThread:280016 [backend.py:_multiprocessing_setup():105] multiprocessing start_methods=spawn, using: spawn
2023-10-18 15:06:40,828 INFO    MainThread:280016 [wandb_init.py:init():624] backend started and connected
2023-10-18 15:06:40,832 INFO    MainThread:280016 [wandb_init.py:init():715] updated telemetry
2023-10-18 15:06:40,832 INFO    MainThread:280016 [wandb_init.py:init():748] communicating run to backend with 90.0 second timeout
2023-10-18 15:06:55,956 WARNING MainThread:280016 [wandb_init.py:init():1187] interrupted
Traceback (most recent call last):
  File "C:\Users\sari\AppData\Local\anaconda3\lib\site-packages\wandb\sdk\wandb_init.py", line 1165, in init
    run = wi.init()
  File "C:\Users\sari\AppData\Local\anaconda3\lib\site-packages\wandb\sdk\wandb_init.py", line 751, in init
    result = run_init_handle.wait(
  File "C:\Users\sari\AppData\Local\anaconda3\lib\site-packages\wandb\sdk\lib\mailbox.py", line 283, in wait
    found, abandoned = self._slot._get_and_clear(timeout=wait_timeout)
  File "C:\Users\sari\AppData\Local\anaconda3\lib\site-packages\wandb\sdk\lib\mailbox.py", line 130, in _get_and_clear
    if self._wait(timeout=timeout):
  File "C:\Users\sari\AppData\Local\anaconda3\lib\site-packages\wandb\sdk\lib\mailbox.py", line 126, in _wait
    return self._event.wait(timeout=timeout)
  File "C:\Users\sari\AppData\Local\anaconda3\lib\threading.py", line 607, in wait
    signaled = self._cond.wait(timeout)
  File "C:\Users\sari\AppData\Local\anaconda3\lib\threading.py", line 324, in wait
    gotit = waiter.acquire(True, timeout)
KeyboardInterrupt
